# Default Spring Profile
server:
  error:
    include-message: always
frontend:
  url: http://localhost:3000/

backend:
  url: http://localhost:8080/

website:
  domain: localhost

logging:
  level:
    root: INFO
    com.example: DEBUG # package name
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG

---
#for docker

spring:
  config:
    activate:
      on-profile: docker
  web:
    resources:
      add-mappings: false

  datasource:
    url: jdbc:mysql://db-portfolio-do-user-15823121-0.c.db.ondigitalocean.com:25060/defaultdb
    username: ${spring.mysql.username}
    password: ${spring.mysql.password}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect

server:
  error:
    whitelabel:
      enabled: false
    include-binding-errors: always
    include-message: always
  port: 8080

frontend:
  url: http://localhost:3000/

backend:
  url: http://localhost:8080/

website:
  domain: localhost


# Exclude SecurityAutoConfiguration to disable Spring Security auto-configuration
spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.datasource.hikari.initializationFailTimeout: 60000

---
# for production
spring:
  config:
    activate:
      on-profile: prod
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://db-portfolio-do-user-15823121-0.c.db.ondigitalocean.com:25060/defaultdb
    username: ${spring.mysql.username}
    password: ${spring.mysql.password}

  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      platform: mysql
      mode: always
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server:
  error:
    whitelabel:
      enabled: false
    include-binding-errors: always
    include-message: always
  port: 8080

frontend:
  url: https://caleb-portfolio.social/

backend:
  url: https://caleb-porfolio-yo8gp.ondigitalocean.app/

website:
  domain: caleb-portfolio.social

spring.datasource.hikari.initializationFailTimeout: 60000


